/** @type {import('tailwindcss').Config} */
export default {
  darkMode: false,
  prefix: "ab-",
  content: [
    './src/**/*.{ts,tsx,html,js,jsx,md,mdx,svelte,vue}',
	],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        'gray': {
          '50': '#fafafa',
          '100': '#f5f5f5',
          '200': '#e5e5e5',
          '300': '#d4d4d4',
          '400': '#a3a3a3',
          '500': '#737373',
          '600': '#525252',
          '700': '#404040',
          '800': '#262626',
          '900': '#171717',
          '950': '#0a0a0a',
        },
        'coral': {
          '50': 'hsl(15, 57%, 97%)',
          '100': 'hsl(17, 60%, 94%)',
          '200': 'hsl(15, 59%, 89%)',
          '300': 'hsl(15, 59%, 82%)',
          '400': 'hsl(16, 57%, 75%)',
          '500': 'hsl(15, 54%, 60%)',
          '600': 'hsl(16, 46%, 51%)',
          '700': 'hsl(16, 46%, 42%)',
          '800': 'hsl(16, 44%, 35%)',
          '900': 'hsl(15, 40%, 31%)',
          '950': 'hsl(16, 47%, 15%)',
        },
        'amber': {
          '50': 'hsl(47, 75%, 95%)',
          '100': 'hsl(48, 74%, 88%)',
          '200': 'hsl(45, 76%, 77%)',
          '300': 'hsl(42, 76%, 64%)',
          '400': 'hsl(40, 75%, 55%)',
          '500': 'hsl(38, 73%, 47%)',
          '600': 'hsl(33, 75%, 40%)',
          '700': 'hsl(28, 71%, 33%)',
          '800': 'hsl(24, 63%, 29%)',
          '900': 'hsl(21, 57%, 26%)',
          '950': 'hsl(18, 64%, 14%)',
        },
        'midnight': {
          '50': 'hsl(185, 68%, 96%)',
          '100': 'hsl(191, 67%, 90%)',
          '200': 'hsl(191, 66%, 82%)',
          '300': 'hsl(192, 66%, 69%)',
          '400': 'hsl(193, 61%, 53%)',
          '500': 'hsl(194, 67%, 43%)',
          '600': 'hsl(197, 65%, 36%)',
          '700': 'hsl(198, 58%, 31%)',
          '800': 'hsl(199, 49%, 27%)',
          '900': 'hsl(202, 45%, 24%)',
          '950': 'hsl(202, 56%, 15%)',
        },
        'olive': {
          '50': 'hsl(71, 84%, 95%)',
          '100': 'hsl(73, 82%, 89%)',
          '200': 'hsl(75, 83%, 80%)',
          '300': 'hsl(75, 79%, 67%)',
          '400': 'hsl(76, 73%, 55%)',
          '500': 'hsl(77, 75%, 44%)',
          '600': 'hsl(78, 80%, 35%)',
          '700': 'hsl(80, 73%, 27%)',
          '800': 'hsl(79, 64%, 23%)',
          '900': 'hsl(81, 57%, 15%)',
          '950': 'hsl(83, 76%, 10%)',
        },
        border: "hsl(var(--ab-border))",
        input: "hsl(var(--ab-input))",
        ring: "hsl(var(--ab-ring))",
        background: "hsl(var(--ab-background))",
        foreground: "hsl(var(--ab-foreground))",
        primary: {
          DEFAULT: "hsl(var(--ab-primary))",
          foreground: "hsl(var(--ab-primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--ab-secondary))",
          foreground: "hsl(var(--ab-secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--ab-destructive))",
          foreground: "hsl(var(--ab-destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--ab-muted))",
          foreground: "hsl(var(--ab-muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--ab-accent))",
          foreground: "hsl(var(--ab-accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--ab-popover))",
          foreground: "hsl(var(--ab-popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--ab-card))",
          foreground: "hsl(var(--ab-card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--ab-radius)",
        md: "calc(var(--ab-radius) - 2px)",
        sm: "calc(var(--ab-radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--ab-radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--ab-radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      spacing: {
        px: '1px',
        '1': '2px',
        '2': '4px',
        '3': '6px',
        '4': '8px',
        '5': '12px',
        '6': '14px',
      },
      fontSize: {
        px: '2px !important',
        xs: ['8px !important', { lineHeight: '12px !important', letterSpacing: '2px' }],
        sm: ['10px !important', { lineHeight: '14px !important' }],
        base: ['12px !important', { lineHeight: '16px !important' }],
        lg: ['14px !important', { lineHeight: '20px !important' }],
        xl: ['16px !important', { lineHeight: '20px !important' }],
        '2xl': ['18px !important', { lineHeight: '22px !important', letterSpacing: '2px' }],
        '3xl': ['22px !important', { lineHeight: '24px !important' }],
        '4xl': ['28px !important', { lineHeight: '30px !important' }],
        '5xl': ['32px !important', { lineHeight: '34px !important' }],
        '6xl': ['40px !important', { lineHeight: '42px !important' }],
        '7xl': ['48px !important', { lineHeight: '50px !important' }],
        '8xl': ['64px !important', { lineHeight: '66px !important' }],
        '9xl': ['86px !important', { lineHeight: '88px !important' }],
    },    
      fontFamily: {
        heading: ['sans-serif'],
        body: ['sans-serif'],
      },
      backgroundImage: {
        'gradient-b': "linear-gradient(0deg, #eee, #fefefe 21%, #fff 25%, #fff)",
        'gradient-t': "linear-gradient(180deg, #eee, #fefefe 21%, #fff 25%, #fff)",
        'gradient-br': "linear-gradient(-38deg, #eee, #fefefe 21%, #fff 25%, #fff)",
        'gradient-bl': "linear-gradient(38deg, #eee, #fefefe 21%, #fff 25%, #fff)",
        'gradient-tr': "linear-gradient(-130deg, #eee, #fefefe 21%, #fff 25%, #fff)",
        'gradient-tl': "linear-gradient(130deg, #eee, #fefefe 21%, #fff 25%, #fff)"
      }
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require('@tailwindcss/typography'),
  ],
}

