name: GitHub Actions Nightly Build

on:
#  push:
#    branches:
#      - main
jobs:
  build-and-pre-release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Download emebdding model
        run: bun run download-model
      - name: Build the project
        run: bun run build